#spring:
##  main:
##    allow-bean-definition-overriding:
##      true
#  application:
#    name:
#      Ebook-Developmnet
#application:
#  uploaddir:
#    /tmp
management:
  endpoints:
    web:
      exposure:
        include: "*"
hello:
  country: "PL"
  greeting: "Witaj świecie!"
  language: "polish"

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding:
      true
  application:
    name:
      EbookStore
application:
  uploaddir:
    /tmp
